id: elastic-misconfig

info:
  name: Elastic Misconfigurations
  author: glatisant
  severity: high

requests:
  - method: GET
    path:
      - '{{BaseURL}}/'
      - '{{BaseURL}}/_search?q=*'
    matchers:
      - type: word
        words:
          - 'took'
          - 'cluster_name'

