id: kibana-misconfig

info:
  name: Kibana Misconfigurations
  author: glatisant
  severity: high

requests:
  - method: GET
    path:
      - '{{BaseURL}}/'
      - '{{BaseURL}}/api/console/proxy?uri=_mapping'
      - '{{BaseURL}}/app/kibana/'
    matchers:
      - type: word
        words:
          - 'kibanaWelcomeView'
          - 'cluster_uuid'

